### ISSUE TITLE
Remove extra config from pillar.example

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/chrony-formula#6]
Comment on Pull request #5 from @aboe76   

"_can you please update the pillar.example. and remove extra config part.._"

I verified #5 against pillar.example below because defaults.sls now has good defaults instead.  

**pillar.example**
```
chrony:
  config:
```
@aboe76  Should pillar.example look like this?  If yes I'll raise PR now.

**Comment by aboe76** [comment]
pillar which works on Archlinux:
```
chrony:
  keygen: True
  ntpservers:
    - 'ntp0.nl.net'
    - 'ntp1.nl.net'
    - 'ntp2.nl.net'
    - 'ntp.xs4all.nl'
    - '0.nl.pool.ntp.org'
    - '1.nl.pool.ntp.org'
    - '2.nl.pool.ntp.org'
    - '3.nl.pool.ntp.org'
```
